use std::collections::HashSet;
use std::path::PathBuf;

use merlint::history;
use merlint::parser;
use merlint::profile;

use super::helpers::{agent_kind_str, analyze_session, load_from_source, store_to_history};

pub async fn run(interval: u64, target: PathBuf, report: bool) -> anyhow::Result<()> {
    tracing_subscriber::fmt()
        .with_target(false)
        .with_level(true)
        .init();
    eprintln!("merlint daemon started (interval: {}s)", interval);
    eprintln!("Press Ctrl+C to stop.\n");

    let mut last_session_count: i64 = 0;
    let mut analyzed_files: HashSet<String> = HashSet::new();

    loop {
        let sources = parser::discover::discover_agents();
        let mut new_sessions = 0;

        for src in &sources {
            let sessions = parser::discover::list_sessions(&src.session_dir);
            for s in &sessions {
                let file_key = format!(
                    "{}:{}",
                    s.display(),
                    s.metadata()
                        .ok()
                        .and_then(|m| m.len().into())
                        .unwrap_or(0u64)
                );
                if analyzed_files.contains(&file_key) {
                    continue;
                }
                if let Ok(session) = load_from_source(s, src.kind) {
                    if !session.entries.is_empty() {
                        let (ts, ca, ea) = analyze_session(&session);
                        store_to_history(
                            &session.id,
                            &s.display().to_string(),
                            agent_kind_str(src.kind),
                            &ts,
                            &ea,
                            &ca,
                        );
                        new_sessions += 1;
                        analyzed_files.insert(file_key);
                    }
                }
            }
        }

        if let Ok(db) = history::db::HistoryDb::open() {
            let current_count = db.session_count().unwrap_or(0);
            if current_count > last_session_count {
                last_session_count = current_count;
                eprintln!(
                    "[{}] {} sessions in history ({} new this cycle)",
                    chrono::Local::now().format("%H:%M:%S"),
                    current_count,
                    new_sessions
                );

                if let Ok(prof) = profile::engine::build_profile(&db) {
                    if !prof.recommendations.is_empty() {
                        eprintln!("  Recommendations:");
                        for rec in &prof.recommendations {
                            eprintln!("    -> {}", rec);
                        }
                    }
                }

                if current_count >= 3 {
                    if let Ok(freq) = db.tool_frequency() {
                        let all_tools: Vec<String> =
                            freq.iter().map(|f| f.tool_name.clone()).collect();
                        if let Ok(rec) = profile::engine::recommend_pruning(&db, &all_tools) {
                            if !rec.prune.is_empty() {
                                let config = serde_json::json!({
                                    "description": "Auto-generated by merlint daemon",
                                    "confidence": rec.confidence,
                                    "data_sessions": rec.data_sessions,
                                    "allowed_tools": rec.keep,
                                    "pruned_tools": rec.prune,
                                    "updated_at": chrono::Local::now().to_rfc3339(),
                                });
                                let config_path = target.join(".merlint-tools.json");
                                if let Ok(json) = serde_json::to_string_pretty(&config) {
                                    let _ = std::fs::write(&config_path, &json);
                                    eprintln!(
                                        "  Updated {} (pruned {} tools, confidence {:.0}%)",
                                        config_path.display(),
                                        rec.prune.len(),
                                        rec.confidence * 100.0
                                    );
                                }
                            }
                        }
                    }
                }

                if report {
                    if let Ok(prof) = profile::engine::build_profile(&db) {
                        let report_path = target.join("merlint-report.json");
                        let report_data = serde_json::json!({
                            "generated_at": chrono::Local::now().to_rfc3339(),
                            "sessions_analyzed": prof.stats.session_count,
                            "total_tokens": prof.stats.total_tokens,
                            "avg_tokens_per_session": prof.stats.avg_tokens_per_session,
                            "avg_cache_hit": prof.stats.avg_cache_hit,
                            "habits": prof.habits.iter().map(|h| {
                                serde_json::json!({
                                    "name": h.name,
                                    "description": h.description,
                                    "severity": format!("{:?}", h.severity),
                                })
                            }).collect::<Vec<_>>(),
                            "trends": prof.trends.iter().map(|t| {
                                serde_json::json!({
                                    "metric": t.metric,
                                    "direction": format!("{:?}", t.direction),
                                    "description": t.description,
                                })
                            }).collect::<Vec<_>>(),
                            "tool_frequency": prof.tool_freq.iter().map(|f| {
                                serde_json::json!({
                                    "tool": f.tool_name,
                                    "total_calls": f.total_calls,
                                    "session_count": f.session_count,
                                })
                            }).collect::<Vec<_>>(),
                            "recommendations": prof.recommendations,
                        });
                        if let Ok(json) = serde_json::to_string_pretty(&report_data) {
                            let _ = std::fs::write(&report_path, &json);
                            eprintln!("  Report saved to {}", report_path.display());
                        }
                    }
                }
            } else {
                eprintln!(
                    "[{}] No new sessions.",
                    chrono::Local::now().format("%H:%M:%S")
                );
            }
        }

        tokio::time::sleep(tokio::time::Duration::from_secs(interval)).await;
    }
}
