use std::path::Path;
use colored::*;

use crate::optimizer::plan::*;
use crate::optimizer::config;

/// Apply an optimization plan, writing config files to the target directory
pub fn apply_plan(plan: &OptimizationPlan, target_dir: &Path, dry_run: bool) -> Vec<ApplyResult> {
    let mut results = Vec::new();

    if !dry_run && !target_dir.exists() {
        let _ = std::fs::create_dir_all(target_dir);
    }

    // Generate CLAUDE.md
    let claude_md = config::generate_claude_md(plan);
    if !claude_md.is_empty() {
        let path = target_dir.join("CLAUDE.md");
        results.push(apply_file(&path, &claude_md, "CLAUDE.md (optimization guide)", dry_run));
    }

    // Generate tools allowlist
    if let Some(allowlist) = config::generate_tools_allowlist(plan) {
        let path = target_dir.join(".merlint-tools.json");
        results.push(apply_file(&path, &allowlist, "tools allowlist", dry_run));
    }

    results
}

fn apply_file(path: &Path, content: &str, label: &str, dry_run: bool) -> ApplyResult {
    if dry_run {
        return ApplyResult {
            file: path.display().to_string(),
            label: label.to_string(),
            status: ApplyStatus::DryRun,
            content: content.to_string(),
        };
    }

    // If file exists, check if we should merge or overwrite
    let status = if path.exists() {
        match std::fs::read_to_string(path) {
            Ok(existing) => {
                if existing.contains("Generated by merlint") {
                    // Our own file, safe to overwrite
                    match std::fs::write(path, content) {
                        Ok(_) => ApplyStatus::Updated,
                        Err(e) => ApplyStatus::Error(e.to_string()),
                    }
                } else {
                    // User's file exists — append our section
                    let merged = format!("{}\n\n{}", existing.trim_end(), content);
                    match std::fs::write(path, merged) {
                        Ok(_) => ApplyStatus::Merged,
                        Err(e) => ApplyStatus::Error(e.to_string()),
                    }
                }
            }
            Err(e) => ApplyStatus::Error(e.to_string()),
        }
    } else {
        match std::fs::write(path, content) {
            Ok(_) => ApplyStatus::Created,
            Err(e) => ApplyStatus::Error(e.to_string()),
        }
    };

    ApplyResult {
        file: path.display().to_string(),
        label: label.to_string(),
        status,
        content: content.to_string(),
    }
}

pub struct ApplyResult {
    pub file: String,
    pub label: String,
    pub status: ApplyStatus,
    pub content: String,
}

pub enum ApplyStatus {
    Created,
    Updated,
    Merged,
    DryRun,
    Error(String),
}

/// Print optimization plan to terminal
pub fn print_plan(plan: &OptimizationPlan) {
    println!();
    println!("{}", "══════════════════════════════════════════════".bright_cyan());
    println!("{}", "         Optimization Plan".bright_cyan().bold());
    println!("{}", "══════════════════════════════════════════════".bright_cyan());
    println!();

    if plan.is_empty() {
        println!("  {} No optimizations needed — your agent is efficient!", "✓".green());
        println!();
        return;
    }

    println!("  Found {} optimization(s):\n", plan.items.len());

    for (idx, item) in plan.items.iter().enumerate() {
        let severity_icon = match item.severity {
            OptSeverity::High => "!!!".red().bold(),
            OptSeverity::Medium => "!! ".yellow().bold(),
            OptSeverity::Low => "!  ".bright_black().bold(),
        };

        let category = match item.category {
            OptCategory::Tools => "TOOLS".bright_magenta(),
            OptCategory::Cache => "CACHE".bright_blue(),
            OptCategory::Prompt => "PROMPT".bright_yellow(),
            OptCategory::Efficiency => "EFFICIENCY".bright_green(),
        };

        println!("  {}. [{}] [{}] {}", idx + 1, category, severity_icon, item.title.white().bold());
        println!("     {}", item.description.dimmed());

        if item.estimated_savings > 0 {
            println!("     {} ~{} tokens/call", "Saves:".green(), item.estimated_savings);
        }

        match &item.action {
            OptAction::PruneTools { remove, keep } => {
                if !remove.is_empty() && remove.len() <= 10 {
                    println!("     {} {}", "Remove:".red(), remove.join(", "));
                }
                if !keep.is_empty() && keep.len() <= 10 {
                    println!("     {} {}", "Keep:".green(), keep.join(", "));
                }
            }
            OptAction::RestructurePrompt { suggestion } => {
                for line in suggestion.lines() {
                    println!("     {}", line.dimmed());
                }
            }
            _ => {}
        }

        println!();
    }

    let total = plan.total_savings();
    if total > 0 {
        println!(
            "  {} Estimated total savings: ~{} tokens/call",
            ">>".bright_green(),
            total.to_string().green().bold()
        );
    }

    println!();
    println!("{}", "══════════════════════════════════════════════".bright_cyan());
    println!();
}

/// Print apply results
pub fn print_apply_results(results: &[ApplyResult]) {
    println!();
    for r in results {
        let (icon, status_text) = match &r.status {
            ApplyStatus::Created => ("✓".green(), "created"),
            ApplyStatus::Updated => ("✓".green(), "updated"),
            ApplyStatus::Merged => ("✓".green(), "merged into existing"),
            ApplyStatus::DryRun => ("~".yellow(), "would write"),
            ApplyStatus::Error(e) => {
                println!("  {} {} — {}", "✗".red(), r.label, e);
                continue;
            }
        };
        println!("  {} {} {} ({})", icon, status_text, r.label, r.file.dimmed());
    }
    println!();
}
